### ISSUE TITLE
wrong yellow color in default mode (pspg, mc)

### ISSUE THREAD

**Issue by okbob** [TragicWarrior/libvterm#111]
When I run pspg in default mode, then I get yellow as +/- red colour. This issue can be related to changes that I have to do for Fedora30, where I have to dynamically set yellow colour not just like COLOR_YELLOW && A_BOLD attr. 

I use same logic like mc (and I expect so mc is very wide used console application) - when colours are more than 8, then light colours has offset 8 instead attribute A_BOLD. This is heuristic cca 15 years old based probably on fact so terminal designers would to use BOLD just for BOLD fonts, not for increasing colours. More informations you can find in this ticket https://bugzilla.redhat.com/show_bug.cgi?id=1687141

When I use --x256, then colours are displayed correctly

**Comment by okbob** [comment]
probably you can expect so almost all terminals todays has 256 colours, and if parent terminal has least 256 colours, then vterm should to support 256 colours too

**Comment by TragicWarrior** [comment]
The short answer:

16-color mode (which you're describing) is officially only supported by aixterm and xterm-16color termifo entries (maybe some others).  Making 8 color terminals do 16 colors (via A_BOLD and A_BLINK) is a bit of a hack and it works on some terminals and not others.  There is no predictable way of knowing how a 8 color terminal will respond.  As the RedHat developer pointed out, that behavior is not part of ECMA-48 or any other standard.

The long answer;

I spent quite a bit of time on this not too long ago.  Developers who are aware of the "hack" have had to make their own decisions about whether to use it.  The developer of libcaca has taken down some experiment notes regarding this behavior:

https://github.com/cacalabs/libcaca/blob/master/NOTES

When then "hack" fails (because of the underlying terminal), the artifacts are quite annoying (such as having parts of your screen blink for no apparent reason).  The safest thing to do is to support it when the terminal description says it supports 16 colors or more.  Therefore, standard xterm mode in libvterm does not.  Instead 16 color mode is built into --x256 mode as a subset.  (one day --x256 will become the default).  In --x256 mode there are two mechanisms that are supported:

If you invoke the demo program with --x256 and no other flags, the libvterm will just use colors 9 - 15 blindly.  This seems to always work when the underlying terminal truly supports 16 colors or more.  

Alternatively, the demo program allows you to pass in --c16 which emulates colors 9 -15.  Again, the underlying terminal must support more than 8 colors (but must do these days).  Unlike the first method you can define their values in c16_color.def and recompile.

**Comment by okbob** [comment]
When I run vshell in VTE terminal - and I have default configuration, then it does color reduction from 256 colours to 8. pspg correctly send COLOR_YELLOW and A_BOLD (for this situation), and libvterm doesn't do any transformation and send it to VTE, that display these color badly. 

So the core of problem is lost of valid COLOR value. I think so libvterm should to have (maybe partially) respect parent environment. Terminal has 256 colours, but libvterm reports 8.

**Comment by TragicWarrior** [comment]
So libvterm, does inspect the color capabilities of the underlying terminal, just probably not as you imagine.  In --x256 mode, there are some safeguards to make sure you don't exceed the number of colors that can actually be supported.  It doesn't shift into 256 mode though automatically.  Once I get done with the mouse code, I will probably do some more testing and make 256 color mode the default.  

Just out of curiosity, what does your vte definition look like.  My day-to-day work is on Xubuntu 18.04 and the entry looks like this:

```
infocmp vte |grep colors
colors#8, cols#80, it#8, lines#24, pairs#64,
```

**Comment by okbob** [comment]
result of infocmp is same. But I think so it is configured to hicolor by default.

**Comment by TragicWarrior** [comment]
Yes.  Maybe the 16 color hack is involved here.  Old versions of vte did not support it well and newer versions probably do.  If there were a flag to detect these kinds of things, I would leverage it, but unfortunately there are not.  If vte is supporting 16 colors, then --x256 mode will cause it to be used.

**Comment by okbob** [comment]
It depends on configuration - VTE had a options - show bold as "bold as bold font" and "bold as light". What I know it was working every time - but now, VTE developers the option "bold as light" removed as obsolete. VTE quietly expects 256 colors ten years.  Fedora is very fresh distribution with fresh Gnome, so I had to possibility to see this behave very early :(

**Comment by TragicWarrior** [comment]
I'm not surprised at what you described.  I'm on the other end of the spectrum with Ubuntu 18.04.  My distribution moves very slowly (several years behind Debian Stable).  How important is it to you that --x256 become the default?

**Comment by okbob** [comment]
In this moment, my feeling is not important. This issue shows some gap, that should be handled, Probably almost all applications will contain similar switch based on available colours and then will have same problem. So the color information should be processed in dependency on parent environment.

It is credo of Postgres database, less options are better :). Color management should be almost fully automatic (if it is possible), because libvterm should not to lost parent colors, and should not to create more color than are available from parent.

**Comment by TragicWarrior** [comment]
@okbob , in the latest commit to master, the default mode for libvterm is 256 color mode (as long as the underlying terminal supports it).  if that effectively resolves this Issue I would like to close it.

**Comment by okbob** [comment]
It is fixed, thank you
