### ISSUE TITLE
unwanted scrolling artefact with pspg

### ISSUE THREAD

**Issue by okbob** [TragicWarrior/libvterm#139]
I tested pspg and I found unwanted black areas when I scrolled by mouse wheel

[pavel@nemesis libvterm]$ ./vshell --version

Libvterm version: 6.22

![Snímek z 2019-09-13 16-38-47](https://user-images.githubusercontent.com/546675/64871181-fd760080-d644-11e9-8050-2fbc4ab2f023.png)
[vterm-24138.dump.gz](https://github.com/TragicWarrior/libvterm/files/3610479/vterm-24138.dump.gz)

**Comment by TragicWarrior** [comment]
@okbob , sorry for the delay in acknowledging this.  i've been busy on a large batch of work that i just released today.  i'll take a look at this tomorrow.

**Comment by okbob** [comment]
čt 26. 9. 2019 v 23:58 odesílatel TragicWarrior <notifications@github.com>
napsal:

> @okbob <https://github.com/okbob> , sorry for the delay in acknowledging
> this. i've been busy on a large batch of work that i just released today.
> i'll take a look at this tomorrow.
>

it's not a problem

**Comment by TragicWarrior** [comment]
@okbob , can you tell me if in pspg you're relying on bkgdset / wbkgdset to set the "canvas" color?

**Comment by TragicWarrior** [comment]
@okbob , never mind.  I looked at the source code for pspg.  The problem is the use of assume_default_colors().  libvterm assumes that the terminal is white foreground on black background.  When decoding the RI sequence, libvterm performs the scroll and erases the previous row with spaces on a black background.  For most applications this works.  However, the ncurses extension "assume_default_colors" allows a programmer to use something different.  In this case the case of this pspg theme it is white on blue.  Unfortunately, when an application uses the assume_default_colors API extension, libvterm has no way of knowing this has happened.  AFAIK, ncurses emits no control sequence to inform me of that change.

**Comment by okbob** [comment]
Any terminal should to have same information like libvterm, and it's working there. Maybe you are miss some terminal commands about background settings.

**Comment by okbob** [comment]
I can confirm so it is related to `assume_default_colors` I didn't see this artefact.

**Comment by TragicWarrior** [comment]
@okbob , in order for me to handle this gracefully, ncurses will need to emit an OSC to tell me about this change.  I have proposed this to Thomas on the ncurses mailing list.  Whether or not I can deal with it pretty much depends on his answer.

**Comment by okbob** [comment]
po 30. 9. 2019 v 18:14 odesílatel TragicWarrior <notifications@github.com>
napsal:

> @okbob <https://github.com/okbob> , in order for me to handle this
> gracefully, ncurses will need to emit an OSC to tell me about this change.
> I have proposed this to Thomas on the ncurses mailing list. Whether or not
> I can deal with it pretty much depends on his answer.
>
sure

**Comment by okbob** [comment]
I implemented alternative background settings activated by `--no_assume_default_colors` option for testing purposes

**Comment by okbob** [comment]
Previous notice was wrong - I removed using ssume_default_colors (because I used it wrong), but this unwanted artefact is there still. Now I use correctly `wbkgdset(stdscr, COLOR_PAIR(1))`;

**Comment by TragicWarrior** [comment]
@okbob , there's a similar problem with wbkgdset.  libvterm assumes the background color is black and the foreground color is white.  when wbkgdset() is used it changes the way that ncurses internally handles data so that the  

> background is combined (OR'ed) with all non-blank characters that are written into the  window

Once again, libvterm has no way of knowing this.  I posted a question on ncurses mailing list.  In anticipation of it being the proper method, I've created a test called "ed-bkgdset".  It seems to make both "pspg" and "bastet" happy.  Before my change it was impossible to make both applications happy.

**Comment by okbob** [comment]
inside ed-bkgdset pspg works correctly

**Comment by TragicWarrior** [comment]
@okbob , I never got an answer on ncurses mailing list but all of my compatibility testing passed so I merged it into master.  if it all looks good on your end, please close.

**Comment by okbob** [comment]
It's fixed, thank you
